#
# MINNE LAB
#

title: MINNE lab
email: rodmore@kth.se
description: >- # this means to ignore newlines until "baseurl:"
  MINNE lab: Research in biomedical imaging and deep learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.minnelab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  minnelab
future: true
timezone: Europe/Amsterdam
person-default-image: /assets/people/default.jpg

include: ['_people']

# Collections
collections:
  people:
    output: true
    permalink: /:collection/:name/

# Header navigation order
header_pages:
  - people.markdown
  - updates.markdown
  - code.markdown
  - teaching.markdown
  - maia.markdown
  - join-us.markdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
